baseURL: 'http://www.awpsec.net/'
languageCode: en-gb
title: AWPSEC
theme: hugo-PaperMod

author:
    name: "Alex Whittle Palmer"
params:
    profileMode:
        enabled: true
        title: "AWPSEC" # optional default will be site title
        
        #buttons:
        #    - name: Archive
        #      url: "https://github.com"
        #    - name: Github
        #      url: "https://github.com/"

    socialIcons: # optional
        - name: "github"
          url: "https://www.github.com/awpalex"
        - name: "twitter"
          url: "https://www.twitter.com/awp_al"
menu:
    main:
      - name: About
        url: about/
      - name: Contact
        url: contact/
